### CUCUMBER_OPTS for local run
# ENV: TEST_IOS_UDID
# USSAGE: iOs device UDID
ios_udid: 404AF286-C8B2-4206-A8CD-9C134036B25F

### GLOBAL VARIABLES
# ENV: TEST_IOS_PROJECT_DIR
# USSAGE: path to xcode project
predefined_ios_project_dir_absolute_path: /Users/admin/Documents/MP-A3/
# ENV: TEST_IOS_PROJECT_NAME
# USSAGE: project name
predefined_ios_project_name: MobilePro.xcodeproj
# ENV: TEST_IOS_TARGET_NAME
# USSAGE: '-cal' target will be created from this template target
predefined_ios_target_name: MobilePro
# ENV: TEST_UTILS_APP_FOLDER
# USSAGE: path to test utils
predefined_ios_app_dir_absolute_path: /Users/admin/Documents/MP-Tests/apps/

###iOS devices UDID:
#iPhone 4s (C61638F3-1473-470A-A1FD-50AA0C8BB215) (Shutdown)
#iPhone 5 (6B782037-83F2-4F89-8BF3-6D3243632050) (Shutdown)
#iPhone 5s (6419346C-47A7-4A14-919B-8F0FC6E0066D) (Shutdown)
#iPhone 6 (48EBD213-325E-4AB3-9A0F-8C061E13806F) (Shutdown)
#iPhone 6 Plus (C97BD099-2DD5-400A-ACCE-4DCC9066A895) (Shutdown)
#iPhone 6s (17C1CC3C-01E2-4FB1-A986-3FE204003C80) (Shutdown)
#iPhone 6s Plus (49EDE954-9566-4D4F-8F8F-72ED5DBA7126) (Shutdown)
#iPad 2 (FD7859BC-ACEA-4D35-8E2E-7141006F7B28) (Shutdown)
#iPad Retina (41674214-401B-4F2C-AAAD-B5B925310E84) (Booted)
#iPad Air (1910D139-E010-4020-BE24-6144BCED530F) (Shutdown)
#iPad Air 2 (B0D8BEEA-0A7B-4040-B680-4B659585B0AE) (Shutdown)
#iPad Pro (A76D4806-2192-46EF-8BD0-F4EA10CE9DE8) (Shutdown)
