### CUCUMBER_OPTS for local run
# ENV: TEST_IOS_UDID
# USSAGE: iOs device UDID
ios_udid: 404AF286-C8B2-4206-A8CD-9C134036B25F

### GLOBAL VARIABLES
# ENV: TEST_IOS_PROJECT_DIR
# USSAGE: path to xcode project
predefined_ios_project_dir_absolute_path: /Users/admin/Documents/MP-A3/
# ENV: TEST_IOS_PROJECT_NAME
# USSAGE: project name
predefined_ios_project_name: MobilePro.xcodeproj
# ENV: TEST_IOS_TARGET_NAME
# USSAGE: '-cal' target will be created from this template target
predefined_ios_target_name: MobilePro
# ENV: TEST_UTILS_APP_FOLDER
# USSAGE: path to test utils
predefined_ios_app_dir_absolute_path: /Users/admin/Documents/MP-Tests/apps/

###iOS devices UDID:
#env.IPHONE_4S_UDID=C61638F3-1473-470A-A1FD-50AA0C8BB215
#env.IPHONE_5_UDID=6B782037-83F2-4F89-8BF3-6D3243632050
#env.IPHONE_5S_UDID=6419346C-47A7-4A14-919B-8F0FC6E0066D
#env.IPHONE_6_UDID=48EBD213-325E-4AB3-9A0F-8C061E13806F
#env.IPHONE_6_PLUS_UDID=C97BD099-2DD5-400A-ACCE-4DCC9066A895
#env.IPHONE_6S_UDID=17C1CC3C-01E2-4FB1-A986-3FE204003C80
#env.IPHONE_6S_PLUS_UDID=49EDE954-9566-4D4F-8F8F-72ED5DBA7126
#env.IPAD_2_UDID=FD7859BC-ACEA-4D35-8E2E-7141006F7B28
#env.IPAD_RETINA_UDID=41674214-401B-4F2C-AAAD-B5B925310E84
#env.IPAD_AIR_UDID=1910D139-E010-4020-BE24-6144BCED530F
#env.IPAD_AIR_2_UDID=B0D8BEEA-0A7B-4040-B680-4B659585B0AE
#env.IPAD_PRO_UDID=A76D4806-2192-46EF-8BD0-F4EA10CE9DE8
